### ISSUE TITLE
Theming Issues and Cursor too big in terminal

### ISSUE THREAD

**Issue by ghost** [Miriway/Miriway#29] opened 2023-03-27 02:13 UTC
Hey there i came from the discourse, i am using miriway alongside lxqt, and using qterminal v1.2.0, the cursor size is abnormally big inside the terminal but outside its normal how do i fix that, and is theming of qt and gtk apps a expected feature, i mean in sway one can theme qt and gtk apps, i will look this and maybe even help implement theming

**Comment by CapeCrusader321** [comment] 2023-03-27 02:25
The problem here is that on my system, the configuration files doesnt exist in both under /etc/xdg/ and ~/.config/ .

**Comment by AlanGriffiths** [comment] 2023-03-27 08:44
I've not looked into theming as yet, so help is welcome.

I'm not sure which configuration files you're referring to. Are they specific to LXQT components?

AIUI the cursor is typically loaded from by way of `/usr/share/icons/default/index.theme`

This can be overridden by setting `XCURSOR_THEME`, and that can be added to a miral-shell.config. E.g.

    app-env-amend=XCURSOR_THEME=DMZ-White

**Comment by AlanGriffiths** [comment] 2023-03-27 09:00
I can confirm that I also see this with `qterminal`. I also see it running `qterminal` on GNOME desktop, so this seems to be a Qt theming issue.

**Comment by CapeCrusader321** [comment] 2023-03-27 09:01
The issue regarding configuration files was for the miriway one, i cant find the config files of miriway at specified locations

**Comment by AlanGriffiths** [comment] 2023-03-27 09:08
The miriway configuration files can be found according to

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

> $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 
> ...
>  $XDG_CONFIG_DIRS defines the preference-ordered set of base directories to search for configuration files in addition to the $XDG_CONFIG_HOME base directory. The directories in $XDG_CONFIG_DIRS should be seperated with a colon ':'.
> 
> If $XDG_CONFIG_DIRS is either not set or empty, a value equal to /etc/xdg should be used. 

The `miriway` launcher script prepends `/etc/xdg/xdg-miriway` to `XDG_CONFIG_DIRS` so that system defaults can be provided. (And a default `miriway-shell.config` is installed there)

**Comment by CapeCrusader321** [comment] 2023-03-27 09:29
ok, got it, regarding theming for gtk we can try to implement xsettingsd and for qt kvantum can be done, ubuntu sway remix has achieved theming of both gtk and qt apps using nwg and kvantum in sway

**Comment by AlanGriffiths** [comment] 2023-03-28 08:59
Sounds like you're way ahead of me on theming apps. I would be very happy with some help in that area.

**Comment by AlanGriffiths** [comment] 2023-03-28 15:44
Yes, there are some (commented out) examples of this in the default configuration.

And some scripts for configuring example setups in the `example-configs` subdirectory.

(See the [README.md](https://github.com/Miriway/Miriway#readme) file)

**Comment by CapeCrusader321** [comment] 2023-03-29 06:43
> Yes, there are some (commented out) examples of this in the default configuration.
> 
> And some scripts for configuring example setups in the `example-configs` subdirectory.
> 
> (See the [README.md](https://github.com/Miriway/Miriway#readme) file)

Can i use the tools of sway etc. like wallpaper changer, panel etc. with mir directly, i am trying to create a ubuntu flavour remix with a mir native desktop environment called Mira, its quite and very early but i am working on it, i wish to use sway tools, can i do it ?? can i use mir directly with panels etc. or a lot of tweaks will be needed to integrate mir in a DE, from what i read mir itself is a window manager, creating a DE needs a WM, so how do i use Mir as a WM, because i dont find any other executables of Mir other than Miral-app, i will also study egmde, but curently i lack understanding on integrating mir as compositor and wm to form a desktop environment

**Comment by CapeCrusader321** [comment] 2023-03-29 08:25
> 

Where is this XDG_CONFIG_DIRS located ??, i stiill couldnt find miriway config files , would test adding lxqt theming components and if successful will create a pull request ??

**Comment by AlanGriffiths** [comment] 2023-03-29 08:38
> Where is this XDG_CONFIG_DIRS located ??, i stiill couldnt find miriway config files , would test adding lxqt theming components and if successful will create a pull request ??

`XDG_CONFIG_DIRS` is an environment variable.

The `miriway` launcher script prepends `/etc/xdg/xdg-miriway` to `XDG_CONFIG_DIRS` so that system defaults can be provided. (And a default `miriway-shell.config` is installed there)

The way to test things is to create your `miriway-shell.config` in `~/.config` (as described in [README.md](https://github.com/Miriway/Miriway#readme), and done by the scripts in the `example-configs` subdirectory.

**Comment by CapeCrusader321** [comment] 2023-03-29 12:57
Now everything is clear but for some unknown reason, miriways wont appear in the login session and will open a blank black empty screen, i now understand that miriway stores its files under /usr/local, while the sessions that have to appear in the login session are in /usr, this was not a problem earlier started today itself, i did multiple reinstallations of miriway but it wont work or even appear in the login screen, i will try installing miriway under usr if possible

**Comment by AlanGriffiths** [comment] 2023-03-29 13:36
> i now understand that miriway stores its files under /usr/local/share/wayland-sessions , /usr.local/etc/xdg

Oh. I hadn't noticed that. That comes from 1363ae0452c5093f84418bc65354e93796caec65. I will investigate when I have time

**Comment by CapeCrusader321** [comment] 2023-03-29 13:50
> > i now understand that miriway stores its files under /usr/local/share/wayland-sessions , /usr.local/etc/xdg
> 
> Oh. I hadn't noticed that. That comes from [1363ae0](https://github.com/Miriway/Miriway/commit/1363ae0452c5093f84418bc65354e93796caec65). I will investigate when I have time

How do i contribute miriway uninstaller uninstaller script for miriway, this will be the first contribution, can you help me out by explaining how do i add the uninstaller bash script using pull requests

**Comment by CapeCrusader321** [comment] 2023-03-30 05:59
How can i use miriway in other projects for example i wish to create a Modular yet Advanced Desktop Environment  Mira, the proposal is that it will use miriway as a back-end for compositing and window management but will have a session greeter like GDM,  A wayland panel, terminal, app menu and a configuration tool (swaybg) to change wallpaper etc., i am working on it but its not yet clear how do i implement miriway, using miriway is a sound decision since it will reduce almost half of the efforts needed to create Mira, but i lack understanding on how will i implement panels, launchers etc. atop miriway, i am planning to use launchers, panels etc. from nwg-project, they don't pack deb for ubuntu etc. but i will see that, using the example configs, few things are clear but i need more clarity, also i need to understand what portion of mirriway from this project i can separate to implement it in a different repo of Mira, since this repo currently holds configs related to snap etc. which isn't going to be useful for a native desktop environment

**Comment by CapeCrusader321** [comment] 2023-03-30 11:26
> > i now understand that miriway stores its files under /usr/local/share/wayland-sessions , /usr.local/etc/xdg
> 
> Oh. I hadn't noticed that. That comes from [1363ae0](https://github.com/Miriway/Miriway/commit/1363ae0452c5093f84418bc65354e93796caec65). I will investigate when I have time

For some obvious reason my touchpad click wont work, i tried to enable touchpad click using gsettings command line option but it still wont work am using libinput atop lubuntu 22.04, any suggestions or solutions ??

**Comment by AlanGriffiths** [comment] 2023-03-30 11:51
> For some obvious reason my touchpad click wont work, i tried to enable touchpad click using gsettings command line option but it still wont work am using libinput atop lubuntu 22.04, any suggestions or solutions ??

I'm not entirely sure I've understood your problem, but this sounds like a problem with libinput which Mir uses for input devices. Does this describe what you are experiencing?

https://wayland.freedesktop.org/libinput/doc/latest/touchpads.html#clickpads

**Comment by CapeCrusader321** [comment] 2023-03-30 13:27
> > For some obvious reason my touchpad click wont work, i tried to enable touchpad click using gsettings command line option but it still wont work am using libinput atop lubuntu 22.04, any suggestions or solutions ??
> 
> I'm not entirely sure I've understood your problem, but this sounds like a problem with libinput which Mir uses for input devices. Does this describe what you are experiencing?
> 
> https://wayland.freedesktop.org/libinput/doc/latest/touchpads.html#clickpads

From the above i can only relate that my touchpad is a clickpad with two physical buttons (left/right), the problem is that i have to select everything with the two keys as the middle portion of the touchpad (above the two keys) wont work on wayland though works on xorg..

**Comment by CapeCrusader321** [comment] 2023-03-30 14:36
Hey @AlanGriffiths , is there anyway that this could be enabled in miriway ??
This issue staes that touchpad tap to click can only be enabled through configuration in the config file etc.
 --> https://github.com/swaywm/sway/issues/365

**Comment by AlanGriffiths** [comment] 2023-03-30 15:51
> enabled in miriway

This is something that would need to be addressed by Mir (and then Miriway would get it for free).

Here's a project that might be of use to you as a workaround: https://gitlab.com/warningnonpotablewater/libinput-config

**Comment by CapeCrusader321** [comment] 2023-03-30 17:41
Thanks will try the workaround..

**Comment by CapeCrusader321** [comment] 2023-03-31 03:50
> > enabled in miriway
> 
> This is something that would need to be addressed by Mir (and then Miriway would get it for free).
> 
> Here's a project that might be of use to you as a workaround: https://gitlab.com/warningnonpotablewater/libinput-config

Sadly using the workaround makes the miriway session unusable, i mean after configuring i cant enter the miriway session, it always comes back to the login manager instead of logging in to miriway session.
As per instruction i created a libinput.conf under /etc and followed build instruction, it gets installed but makes miriway session unusable, uninstalling it fixes the issue

**Comment by CapeCrusader321** [comment] 2023-03-31 15:01
hey there @AlanGriffiths  is there any way i could integrate swaylock, swayidle , lightdm etc. because without them miriway looks quite bare-bones and useless, i tried using swaylock and sway idle etc. in the .config but they wont work, i am also looking a way by which launcher, panel or other apps with option to logout/Quit emulate  ctrl+shift+backspace, as this will make it more feature complete and much better integrated with miriway

**Comment by AlanGriffiths** [comment] 2023-03-31 15:28
I know of no reason Miriway wouldn't work with lightdm, but I haven't tried it. (It works with GDM and SSDM). What problem do you see?

You have to find out what goes wrong with swaylock & swayidle, then set things up so they work.

Sending SIGTERM to miriway-shell ought to close it: `killall miriway-shell`

**Comment by CapeCrusader321** [comment] 2023-04-01 05:22
> I know of no reason Miriway wouldn't work with lightdm, but I haven't tried it. (It works with GDM and SSDM). What problem do you see?
> 
> You have to find out what goes wrong with swaylock & swayidle, then set things up so they work.
> 
> Sending SIGTERM to miriway-shell ought to close it: `killall miriway-shell`

The problem with lightdm was on my part, sorry for that, is there anyway with which i can start miriway with the following script, the script is intended to improve theming for both qt5ct and gtk, will open a pull request if we can somehow make it work

[MiraStart.sh.tar.gz](https://github.com/Miriway/Miriway/files/11128506/MiraStart.sh.tar.gz)

**Comment by CapeCrusader321** [comment] 2023-04-01 11:28
@AlanGriffiths  the workaround for touchpad or libinput config even after multiple try and config i have concluded that it breaks Mir as a whole since not only miriway but also mir shell wont work if choosing them through sddm during login, they never allow login if the workaround is initialized, trying to log in wiill bring back one to the sddm screen after a blank black screen, is there any way we can find the reason behind this ?? Is there something module or tweaks needed by Mir to work with the workaround,uninstalling the workaround and its configs fixes the problem but using Miriway with a Paralyzed Touchpad is Frustrating/Sad/Pathetic since i have to use my touch-pad buttons, which will surely get damaged in the long run if this thing continues but the fun fact is a external connected mouse works fine but i dont have space for plugs for a extra mouse..

**Comment by AlanGriffiths** [comment] 2023-04-01 13:02
I have no idea what problem is occurring. Have you looked at the logs?

**Comment by CapeCrusader321** [comment] 2023-04-01 13:19
> I have no idea what problem is occurring. Have you looked at the logs?

Where are these logs located ??, finding them, i have removed the workaround since it breaks miriway completely but will add again to test and cath the logs..

**Comment by AlanGriffiths** [comment] 2023-04-01 13:28
I'd start with `/var/log/syslog`

**Comment by CapeCrusader321** [comment] 2023-04-01 13:55
Ok onto it, my preliminary investigation suggests its due to configuring meson to make the workaround work with Snap Packages

**Comment by CapeCrusader321** [comment] 2023-04-06 14:07
@AlanGriffiths  Is there anyway i force Miriway to center windows by default, lots of application in miriway goes under the screen, can you tell me a way with which i can force miriway to center app windows by deafult

**Comment by AlanGriffiths** [comment] 2023-04-06 14:13
> @AlanGriffiths Is there anyway with which i can force Miriway to center windows by default, lots of application in miriway goes under the screen, can you tell me a way with which i can force miriway to center app windows by default

Miriway uses Mir's `MinimalWindowManager` which centres new windows on the active output. So I don't understand what you want to change.

**Comment by CapeCrusader321** [comment] 2023-04-06 14:46
> 

The problem is as i said a lot of windows when opened goes under the screen i mean appear half, i was wondering any way with which i could get them fixed on the screen in a center position

**Comment by AlanGriffiths** [comment] 2023-04-06 15:43
I can only imagine the app you are having problems with creates the window at one size and, before it is mapped, resizes to a larger size. Not something I've noticed being a problem.

**Comment by CapeCrusader321** [comment] 2023-04-06 16:56
> I can only imagine the app you are having problems with creates the window at one size and, before it is mapped, resizes to a larger size. Not something I've noticed being a problem.

ok then this isnt a problem either, something specific to my use-case, well atleast this issue shouldnt be specific to my setup , swaybg wont work in miriway , i mean i cant change the wallpaper with swaybg once i am in the miriway session, it always spits error and wont work any idea on this i am still unable to get miriway work with sway-lock and idle these both are some must required things for DE although i am still working on it but help will be grateful

**Comment by AlanGriffiths** [comment] 2023-04-06 19:22
> swaybg wont work in miriway , i mean i cant change the wallpaper with swaybg once i am in the miriway session, it always spits error and wont work

Obviously swaybg is working with Miriway. The problem you are encountering is that Miriway is selective in which Wayland extensions it allows to apps. Some are reserved for "shell components" that are started by Miriway.

There are several options:

1. you can simply enable all extensions for all apps:
`add-wayland-extensions=all`

2. you can add the specific extension for all apps:
`add-wayland-extensions=zwlr_layer_shell_v1`

3. You can add code to Miriway to enable the reserved extensions for some apps it doesn't start itself.

> i am still unable to get miriway work with sway-lock and idle these both are some must required things for DE although i am still working on it but help will be grateful

I don't know why these are not working, I've not tried them. You have to look at any errors logged to see what the problem is. Then, if possible, fix it.

**Comment by CapeCrusader321** [comment] 2023-04-17 04:11
> > swaybg wont work in miriway , i mean i cant change the wallpaper with swaybg once i am in the miriway session, it always spits error and wont work
> 
> Obviously swaybg is working with Miriway. The problem you are encountering is that Miriway is selective in which Wayland extensions it allows to apps. Some are reserved for "shell components" that are started by Miriway.
> 
> There are several options:
> 
>     1. you can simply enable all extensions for all apps:
>        `add-wayland-extensions=all`
> 
>     2. you can add the specific extension for all apps:
>        `add-wayland-extensions=zwlr_layer_shell_v1`
> 
>     3. You can add code to Miriway to enable the reserved extensions for some apps it doesn't start itself.
> 
> 
> > i am still unable to get miriway work with sway-lock and idle these both are some must required things for DE although i am still working on it but help will be grateful
> 
> I don't know why these are not working, I've not tried them. You have to look at any errors logged to see what the problem is. Then, if possible, fix it.

@AlanGriffiths  The enabling of all extensions does the work for swaybg although the terminal with the swaybg command must be kept open to make it work more like a specific issue to swaybg, in this long week i have been learning to write and create a new  gsetting schema for DEs not much of a complex thing but i will soon try to bring that here.

**Comment by AlanGriffiths** [comment] 2023-04-17 08:42
> the terminal with the swaybg command must be kept open to make it work more like a specific issue to swaybg

This is not a swaybg issue. You need to disown the process before closing the terminal. Assuming you're using bash this would be something like:

    swaybg -i /usr/share/backgrounds/warty-final-ubuntu.png & disown

**Closed** 2024-08-29 14:31 UTC
Labels: enhancement
